### ISSUE TITLE
Redirect to /api/cart/line-items when adding item to cart

### ISSUE THREAD

**Issue by bitcoinvsalts** [lambda-curry/medusa2-starter#33]
i installed this repo and everything seems to be working fine until I try to add a new item into the cart. it redirects me to http://localhost:3000/api/cart/line-items to shows the json content of the API result. any idea why it s not adding the item to the cart like in the demo?

**Comment by dwene** [comment]
Interesting. That happens sometimes when javascript isn't running in your browser. What browser are you using?

**Comment by bitcoinvsalts** [comment]
thanks for your reply. i am using chrome on macos.
